backend:
  name: git-gateway
  branch: latest
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: 'public/assets/blog' # Folder where user uploaded files should go
public_folder: '/assets/blog'

collections: # A list of collections the CMS should be able to edit
  - name: 'posts' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Blog Posts'
    label_singular: 'Blog Post' # Used in the UI, ie.: "New Post"
    folder: 'src/pages/posts' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    delete: true
    fields: # The fields each document in this collection have
      - { name: 'title', widget: 'string', label: 'Post Title' }
      - { name: 'publishDate', widget: 'datetime', format: 'DD MMM YYYY', date_format: 'DD MMM YYYY', time_format: false, label: 'Publish Date' }
      - { name: 'author', widget: 'string', label: 'Author Name', required: false }
      - { name: 'authorURL', widget: 'string', label: 'Author URL', required: false }
      - { name: 'description', widget: 'string', label: 'Description', required: false }
      - { name: 'body', widget: 'markdown', label: 'Post Body' }
      - { name: 'layout', widget: 'select', default: '../../layouts/BlogPost.astro', options: [ { label: 'Blog Post', value: '../../layouts/BlogPost.astro' }, ] }